-- SQL GAME HELL YEAH

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE room_exits CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; 
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE monsters CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; 
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE players CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; 
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE rooms CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; 
    END IF;
END;
/

CREATE TABLE players (
    player_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50),
    current_room NUMBER,
    hp NUMBER DEFAULT 100
);

CREATE TABLE rooms (
    room_id NUMBER PRIMARY KEY,
    description VARCHAR2(500)
);

CREATE TABLE room_exits (
    from_room NUMBER,
    direction VARCHAR2(10),
    to_room NUMBER
);

CREATE TABLE monsters (
    monster_id NUMBER PRIMARY KEY,
    room_id NUMBER,
    name VARCHAR2(50),
    hp NUMBER,
    status VARCHAR2(20) DEFAULT 'alive'
);